initials = ['b', 'p', 'm',  'f', 'd', 't', 'n', 'l', 'g', 'k', 'h',
            'j', 'q', 'x', 'zh', 'ch', 'sh', 'r', 'z', 'c', 's', 'y', 'w']
finals = ['a', 'e', 'i', 'o', 'u', 'v',
          'ai', 'ao', 'ei', 'ia', 'iao', 'ie', 'iou', 'ou', 'ua', 'uai', 've', 'uei', 'uo',
          'an', 'en', 'ian', 'in', 'uan', 'van', 'uen', 'vn',
          'ang', 'eng', 'iang', 'ing', 'iong', 'ong', 'uang', 'ueng', 'er']

initials_2_phones = {'b': 'b',
                     'p': 'p',
                     'm': 'm',
                     'f': 'f',
                     'd': 'd',
                     't': 't',
                     'n': 'n',
                     'l': 'l',
                     'g': 'g',
                     'k': 'k',
                     'h': 'h',
                     'j': 'j',
                     'q': 'q',
                     'x': 'x',
                     'zh': 'zh',
                     'ch': 'ch',
                     'sh': 'sh',
                     'r': 'r',
                     'z': 'z',
                     'c': 'c',
                     's': 's',
                     'y': 'vv',
                     'w': 'uu'}